export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const INCREMENT_CART_ITEM_QUANTITY = "INCREMENT_CART_ITEM_QUANTITY";
export const DECREMENT_CART_ITEM_QUANTITY = "DECREMENT_CART_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const DISPLAY_CART_ITEM = "DISPLAY_CART_ITEM";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CONVERT_PRODUCT_PRICE = "CONVERT_PRODUCT_PRICE";
export const GET_CURRENCY = "GET_CURRENCY";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const SET_CURRENCY_SYMBOL = "SET_CURRENCY_SYMBOL";
export const TOTAL_PRICE = "TOTAL_PRICE";
export const DISABLE_BUTTON = "DISABLE_BUTTON";

export const ADD_ATTRIBUTES = "ADD_ATTRIBUTES";
export const UPDATE_ATTRIBUTES = "UPDATE_ATTRIBUTES";
